.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. alisinabit_qt test_alisinabit_qt
clean: FORCE
	$(MAKE) -C .. alisinabit_qt_clean test_alisinabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_alisinabit_qt_check
alisinabit-qt alisinabit-qt.exe: FORCE
	 $(MAKE) -C .. alisinabit_qt
